import Head from "next/head";
import DescWithPictureFS from "../components/global/DescWithPictureFS";
import PageHero from "../components/global/PageHero";
import TextBlock from "../components/global/TextBlock";

export default function Serives() {
    return (
        <>
            <Head>
                <title>Honest Towing & Roadside | Services</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <PageHero 
                    heading = 'Services'
                    image = 'carcrash.jpg'
                    imageAlt = 'image alt'
                    pageDesc = "It's simple! We are the towing company that actually puts our customer's first. We understand 
                    that needing emergency car services doesn't make anyone's day better, so we take it upon us to 
                    do whatever it takes to make your life easier. We respond fast and are availible 24/7 whenever 
                    you need us!"
                />
                <TextBlock 
                    text = "It's simple! We are the towing company that actually puts our customer's first. We understand 
                    that needing emergency car services doesn't make anyone's day better, so we take it upon us to 
                    do whatever it takes to make your life easier. We respond fast and are availible 24/7 whenever 
                    you need us!"
                />
                <DescWithPictureFS 
                    image = 'carcrash.jpg'
                    imageAlt = 'image alt'
                    title = 'Towing'
                    text = "It's simple! We are the towing company that actually puts our customer's first. We understand 
                    that needing emergency car services doesn't make anyone's day better, so we take it upon us to 
                    do whatever it takes to make your life easier. We respond fast and are availible 24/7 whenever 
                    you need us!"
                    reversed = {true}
                />
                <DescWithPictureFS 
                    image = 'carcrash.jpg'
                    imageAlt = 'image alt'
                    title = 'Roadside Assisstance'
                    text = "It's simple! We are the towing company that actually puts our customer's first. We understand 
                    that needing emergency car services doesn't make anyone's day better, so we take it upon us to 
                    do whatever it takes to make your life easier. We respond fast and are availible 24/7 whenever 
                    you need us!"
                    reversed = {false}
                />
                <DescWithPictureFS 
                    image = 'carcrash.jpg'
                    imageAlt = 'image alt'
                    title = 'Tire Change'
                    text = "It's simple! We are the towing company that actually puts our customer's first. We understand 
                    that needing emergency car services doesn't make anyone's day better, so we take it upon us to 
                    do whatever it takes to make your life easier. We respond fast and are availible 24/7 whenever 
                    you need us!"
                    reversed = {true}
                />
                <DescWithPictureFS 
                    image = 'carcrash.jpg'
                    imageAlt = 'image alt'
                    title = 'Jump Start'
                    text = "It's simple! We are the towing company that actually puts our customer's first. We understand 
                    that needing emergency car services doesn't make anyone's day better, so we take it upon us to 
                    do whatever it takes to make your life easier. We respond fast and are availible 24/7 whenever 
                    you need us!"
                    reversed = {false}
                />
                <DescWithPictureFS 
                    image = 'carcrash.jpg'
                    imageAlt = 'image alt'
                    title = 'Fuel Delivary'
                    text = "It's simple! We are the towing company that actually puts our customer's first. We understand 
                    that needing emergency car services doesn't make anyone's day better, so we take it upon us to 
                    do whatever it takes to make your life easier. We respond fast and are availible 24/7 whenever 
                    you need us!"
                    reversed = {true}
                />
                <DescWithPictureFS 
                    image = 'carcrash.jpg'
                    imageAlt = 'image alt'
                    title = 'Lockout'
                    text = "It's simple! We are the towing company that actually puts our customer's first. We understand 
                    that needing emergency car services doesn't make anyone's day better, so we take it upon us to 
                    do whatever it takes to make your life easier. We respond fast and are availible 24/7 whenever 
                    you need us!"
                    reversed = {false}
                />
                <TextBlock 
                    text = "It's simple! We are the towing company that actually puts our customer's first. We understand 
                    that needing emergency car services doesn't make anyone's day better, so we take it upon us to 
                    do whatever it takes to make your life easier. We respond fast and are availible 24/7 whenever 
                    you need us!"
                />
            </main>
        </>
    );
  }